[build-system]
requires = [
    "dataclasses-json",
    "pyside6",
    "pyside6-helpers @ git+https://github.com/MrFrangipane/pyside6-helpers@main",
    "python-helpers @ git+https://github.com/MrFrangipane/python-helpers@main",
    "setuptools",
    "telnetlib3",
]
build-backend = "setuptools.build_meta"

[project]
name = "grandma2telnet"
description = "Telnet automation tool for Grand MA 2"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
authors = [
  { name = "Frangitron", email = "contact@frangitron.com" }
]
maintainers = [
  { name = "Frangitron", email = "contact@frangitron.com" }
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3 :: Only",
]
keywords = ["python", "frangitron", "gui"]
dynamic = ["version"]

[tool.setuptools]
include-package-data = true

[tool.hatch.metadata]
allow-direct-references = true
